### ISSUE TITLE
Can not convert the keras - moiblenet, H5 model to tensorflow Pb model 

### ISSUE THREAD

**Issue by zhaoleistar** [amir-abdi/keras_to_tensorflow#16] opened 2018-01-12 10:38 UTC
I use the tool to convert the keras- moiblenet model to pb model , but   An error has occurred : ValueError: Unknown activation function:relu6.

The detail info is:

 File "keras_to_tensorflow.py", line 95, in <module>
    net_model = load_model(weight_file_path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/models.py", line 240, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/models.py", line 314, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 140, in deserialize_keras_object
    list(custom_objects.items())))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/topology.py", line 2490, in from_config
    process_layer(layer_data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/topology.py", line 2476, in process_layer
    custom_objects=custom_objects)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 142, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/topology.py", line 1253, in from_config
    return cls(**config)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/layers/core.py", line 291, in __init__
    self.activation = activations.get(activation)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/activations.py", line 95, in get
    return deserialize(identifier)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/activations.py", line 87, in deserialize
    printable_module_name='activation function')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 160, in deserialize_keras_object
    ':' + function_name)
ValueError: Unknown activation function:relu6

**Comment by amir-abdi** [comment] 2018-01-12 18:58
My first thoughts are following [this thread](https://github.com/keras-team/keras/issues/7431).
As it is suggested there, MobileNet has some customized layers, including relu6. For the conversion to work, add the following lines prior to loading the model:

```
from keras.utils.generic_utils import CustomObjectScope
with CustomObjectScope({'relu6': keras.applications.mobilenet.relu6,'DepthwiseConv2D': keras.applications.mobilenet.DepthwiseConv2D}):
    model = load_model('weights.hdf5')
```

**Comment by amir-abdi** [comment] 2018-02-06 20:43
@zhaoleistar  I assume the issue is now resolved and will be closing it.
Reopen otherwise.

**Closed by amir-abdi** 2018-02-06 20:43 UTC

**Comment by SteveIb** [comment] 2018-10-21 08:50
Hi Amir,

I tried to change the loading model as following : 

#model = keras.models.load_model(input_model_path)
        from keras.utils.generic_utils import CustomObjectScope
        with CustomObjectScope({'relu6': keras.applications.mobilenet.relu6,'DepthwiseConv2D': keras.applications.mobilenet.DepthwiseConv2D}):
            model = load_model('xxxx.h5')
        return model

I'm getting the following error 

Using TensorFlow backend.
Traceback (most recent call last):
  File "keras_to_tensorflow.py", line 169, in <module>
    app.run(main)
  File "/home/dell/anaconda2/envs/py35/lib/python3.5/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/dell/anaconda2/envs/py35/lib/python3.5/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "keras_to_tensorflow.py", line 115, in main
    model = load_model(FLAGS.input_model, FLAGS.input_model_json)
  File "keras_to_tensorflow.py", line 64, in load_model
    model = load_model('xxxx.h5')
TypeError: load_model() missing 1 required positional argument: 'input_json_path'

is that the right place to change the load model file?

I also tried to put something like this       
with CustomObjectScope({'relu6': keras.applications.mobilenet.relu6,'DepthwiseConv2D': keras.applications.mobilenet.DepthwiseConv2D}):
            model = load_model(input_model_path)

but still the same error! any hints?
