### ISSUE TITLE
Modified InceptionV3 Keras model wont run in iOS

### ISSUE THREAD

**Issue by madhavajay** [amir-abdi/keras_to_tensorflow#4] opened 2017-07-03 16:36 UTC
I added the pb file outputted by the keras_to_tensorflow notebook to the camera example of TensorFlow iOS however i get the following errors:

```
2017-07-03 15:30:19.127247+0200 tf_camera_example[13801:5065229] 0x170355660 Copy matching assets reply: XPC_TYPE_DICTIONARY  <dictionary: 0x170355660> { count = 3, transaction: 0, voucher = 0x0, contents =
	"Assets" => <data: 0x170474400>: { length = 1229 bytes, contents = 0x62706c6973743030d4010203040506646558247665727369... }
	"Result" => <int64: 0x17042d920>: 0
	"AssetXMLMetadata" => <data: 0x1704743c0>: { length = 307 bytes, contents = 0x62706c6973743030d40102030405061f2058247665727369... }
}
2017-07-03 15:30:19.132701+0200 tf_camera_example[13801:5065229] 0x170355870 Copy assets attributes reply: XPC_TYPE_DICTIONARY  <dictionary: 0x170355870> { count = 1, transaction: 0, voucher = 0x0, contents =
	"Result" => <int64: 0x17042d860>: 1
}
2017-07-03 15:30:19.132829+0200 tf_camera_example[13801:5065229] [MobileAssetError:1] Unable to copy asset attributes
2017-07-03 15:30:19.133159+0200 tf_camera_example[13801:5065229] Could not get attribute 'LocalURL': Error Domain=MobileAssetError Code=1 "Unable to copy asset attributes" UserInfo={NSDescription=Unable to copy asset attributes}
2017-07-03 15:30:19.140440+0200 tf_camera_example[13801:5065229] 0x170355450 Copy matching assets reply: XPC_TYPE_DICTIONARY  <dictionary: 0x170355450> { count = 3, transaction: 0, voucher = 0x0, contents =
	"Assets" => <data: 0x1704751c0>: { length = 1237 bytes, contents = 0x62706c6973743030d4010203040506636458247665727369... }
	"Result" => <int64: 0x17042dcc0>: 0
	"AssetXMLMetadata" => <data: 0x170475280>: { length = 307 bytes, contents = 0x62706c6973743030d40102030405061f2058247665727369... }
}
2017-07-03 15:30:19.144379+0200 tf_camera_example[13801:5065229] 0x170355870 Copy assets attributes reply: XPC_TYPE_DICTIONARY  <dictionary: 0x170355870> { count = 1, transaction: 0, voucher = 0x0, contents =
	"Result" => <int64: 0x17042d720>: 1
}
2017-07-03 15:30:19.144512+0200 tf_camera_example[13801:5065229] [MobileAssetError:1] Unable to copy asset attributes
2017-07-03 15:30:19.145302+0200 tf_camera_example[13801:5065229] Could not get attribute 'LocalURL': Error Domain=MobileAssetError Code=1 "Unable to copy asset attributes" UserInfo={NSDescription=Unable to copy asset attributes}
2017-07-03 15:30:20.389946: E /Users/madhavajay/Desktop/dev/tensorflow/tensorflow/examples/ios/camera/tensorflow_utils.mm:140] Could not create TensorFlow Graph: Invalid argument: No OpKernel was registered to support Op 'Switch' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_INT32]
  device='GPU'; T in [DT_BOOL]
  device='GPU'; T in [DT_STRING]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]

	 [[Node: batch_normalization_188/cond/Switch = Switch[T=DT_BOOL](batch_normalization_95/keras_learning_phase, batch_normalization_95/keras_learning_phase)]]
2017-07-03 15:30:20.396129: F /Users/madhavajay/Desktop/dev/tensorflow/tensorflow/examples/ios/camera/CameraExampleViewController.mm:391] Couldn't load model: Invalid argument: No OpKernel was registered to support Op 'Switch' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_INT32]
  device='GPU'; T in [DT_BOOL]
  device='GPU'; T in [DT_STRING]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]

	 [[Node: batch_normalization_188/cond/Switch = Switch[T=DT_BOOL](batch_normalization_95/keras_learning_phase, batch_normalization_95/keras_learning_phase)]]
(lldb) 
```

**Comment by amir-abdi** [comment] 2017-07-03 20:24
I have not tested on iOS. But I just updated the code to set the `keras_learning_phase = 0`, which might solve your problem. Please test again and let me know.

**Comment by amir-abdi** [comment] 2017-07-12 17:16
@madhavajay I updated the code again. Is your problem solved?

**Comment by madhavajay** [comment] 2017-07-12 18:47
I ended up making a modification to your notebook based on the guide here:
http://blog.stratospark.com/creating-a-deep-learning-ios-app-with-keras-and-tensorflow.html

My code is here:
https://github.com/madhavajay/what-dog
https://github.com/madhavajay/what-dog/blob/master/model_converter/keras_to_tensorflow.ipynb

I'm not exactly sure which parts made it work but I noticed a few things:
1) it wasn't working even with all the middle steps when using the final save step from your notebook, so I replaced it with the final save step from the above guide and it worked... which was weird.

2) The model worked in iOS but not Android.
To get it working in Android I needed to run it through the transform_graph tool. Once that was done the model worked in Android, and the same model file also still worked in iOS.

So yeah not sure why exactly, the two versions of the final pb files are there in the git repo. I can send you the original hdf5 file if you want to take a look.

**Comment by amir-abdi** [comment] 2017-07-13 01:29
My error was that I was setting the `learning_phase` flag after loading the model. Apparently, it had to be the other way around, like this:
```
K.set_learning_phase(0)
net_model = load_model(weight_file_path)
```

We now tried the model which was converted with this code on android, and it works fine.

**Comment by amir-abdi** [comment] 2017-08-31 03:19
@madhavajay  I assume the issue is now resolved and I will close the issue. Otherwise, please re-open it.

**Closed by amir-abdi** 2017-08-31 03:19 UTC

**Comment by madhavajay** [comment] 2017-08-31 08:20
Yes thanks.
